version: '3.8'

services:
  analytics:
    # Build the Docker image from the Dockerfile in this directory
    build: .
    container_name: quantframe-analytics
    # The server reads the QuantFrame database via the QUANTFRAME_DB_PATH
    # environment variable.  You should mount the path to your
    # quantframeV2.sqlite file into the container (e.g. via volumes).
    environment:
      # Path inside the container where the database will be available.
      # By default it points to /data/quantframeV2.sqlite.
      - QUANTFRAME_DB_PATH=/data/quantframeV2.sqlite
      # Port on which the server listens inside the container.
      # Use the ANALYTICS_PORT environment variable to change the host mapping.
      - PORT=3000
    volumes:
      # Mount your QuantFrame database file into the container.  Replace
      # `./quantframeV2.sqlite` on the left with the absolute path to your
      # database file on the host.  The file is mounted read‑only.
      - ./quantframeV2.sqlite:/data/quantframeV2.sqlite:ro
    ports:
      # Map the container's internal port 3000 to a host port.  The host
      # port can be customised by setting the ANALYTICS_PORT environment
      # variable before running docker‑compose (e.g. ANALYTICS_PORT=8080).
      - "${ANALYTICS_PORT:-3000}:3000"
    restart: unless-stopped